default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: zehan
  password: zehan
  host: localhost

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend_production
  username: your_production_database_username
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
